import { Stethoscope, Scissors, GraduationCap, Home } from "lucide-react";
import type { Practice } from "@/components";
import type { ServiceCategory } from "@/components";
import type { Guide } from "@/components";

// Service Categories
export const serviceCategories: ServiceCategory[] = [
  {
    slug: "vets",
    name: "Veterinary Practices",
    description: "Find verified vets and animal hospitals near you",
    icon: Stethoscope,
    practiceCount: 48,
    imageUrl: "https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?w=800&q=80",
  },
  {
    slug: "groomers",
    name: "Dog Groomers",
    description: "Professional grooming services for your pet",
    icon: Scissors,
    practiceCount: 32,
    imageUrl: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=800&q=80",
  },
  {
    slug: "trainers",
    name: "Dog Trainers",
    description: "Certified trainers and behaviorists",
    icon: GraduationCap,
    practiceCount: 24,
    imageUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&q=80",
  },
  {
    slug: "boarding",
    name: "Boarding & Daycare",
    description: "Safe and caring facilities for your pet",
    icon: Home,
    practiceCount: 18,
    imageUrl: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&q=80",
  },
];

// Sample Practices
export const samplePractices: Practice[] = [
  // Veterinary Practices
  {
    id: "1",
    slug: "highgate-veterinary-centre",
    name: "Highgate Veterinary Centre",
    location: "London, UK",
    badgeTier: "outstanding",
    excellenceRank: 9.8,
    category: "vets",
    imageUrl: "https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=400&q=80",
  },
  {
    id: "2",
    slug: "cotswold-pet-hospital",
    name: "The Cotswold Pet Hospital",
    location: "Stroud, UK",
    badgeTier: "excellent",
    excellenceRank: 9.4,
    category: "vets",
    imageUrl: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&q=80",
  },
  {
    id: "3",
    slug: "manchester-animal-care",
    name: "Manchester Animal Care",
    location: "Manchester, UK",
    badgeTier: "verified",
    excellenceRank: 9.6,
    category: "vets",
    imageUrl: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=400&q=80",
  },
  {
    id: "4",
    slug: "bristol-pet-clinic",
    name: "Bristol Pet Clinic",
    location: "Bristol, UK",
    badgeTier: "verified",
    excellenceRank: 9.2,
    category: "vets",
    imageUrl: "https://images.unsplash.com/photo-1600880292203-757bb62b4baf?w=400&q=80",
  },
  {
    id: "5",
    slug: "cambridge-veterinary-group",
    name: "Cambridge Veterinary Group",
    location: "Cambridge, UK",
    badgeTier: "excellent",
    excellenceRank: 9.5,
    category: "vets",
    imageUrl: "https://images.unsplash.com/photo-1606567595334-d39972c85dfd?w=400&q=80",
  },
  {
    id: "6",
    slug: "leeds-animal-hospital",
    name: "Leeds Animal Hospital",
    location: "Leeds, UK",
    badgeTier: "verified",
    excellenceRank: 9.1,
    category: "vets",
    imageUrl: "https://images.unsplash.com/photo-1588943211346-0908a1fb0b01?w=400&q=80",
  },
  {
    id: "7",
    slug: "edinburgh-pet-wellness",
    name: "Edinburgh Pet Wellness Centre",
    location: "Edinburgh, UK",
    badgeTier: "outstanding",
    excellenceRank: 9.7,
    category: "vets",
    imageUrl: "https://images.unsplash.com/photo-1612531386530-97286d97c2d2?w=400&q=80",
  },
  {
    id: "8",
    slug: "birmingham-veterinary-specialists",
    name: "Birmingham Veterinary Specialists",
    location: "Birmingham, UK",
    badgeTier: "excellent",
    excellenceRank: 9.3,
    category: "vets",
    imageUrl: "https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?w=400&q=80",
  },
  {
    id: "9",
    slug: "oxford-animal-clinic",
    name: "Oxford Animal Clinic",
    location: "Oxford, UK",
    badgeTier: "verified",
    excellenceRank: 9.0,
    category: "vets",
    imageUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&q=80",
  },
  {
    id: "10",
    slug: "brighton-coastal-vets",
    name: "Brighton Coastal Vets",
    location: "Brighton, UK",
    badgeTier: "excellent",
    excellenceRank: 9.4,
    category: "vets",
    imageUrl: "https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=400&q=80",
  },
  {
    id: "11",
    slug: "bath-veterinary-hospital",
    name: "Bath Veterinary Hospital",
    location: "Bath, UK",
    badgeTier: "outstanding",
    excellenceRank: 9.6,
    category: "vets",
    imageUrl: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=400&q=80",
  },
  {
    id: "12",
    slug: "york-pet-practice",
    name: "York Pet Practice",
    location: "York, UK",
    badgeTier: "verified",
    excellenceRank: 9.2,
    category: "vets",
    imageUrl: "https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=400&q=80",
  },
  // Groomers
  {
    id: "13",
    slug: "paws-perfection-grooming",
    name: "Paws & Perfection Grooming",
    location: "London, UK",
    badgeTier: "outstanding",
    excellenceRank: 9.7,
    category: "groomers",
    imageUrl: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=400&q=80",
  },
  {
    id: "14",
    slug: "the-dog-spa-manchester",
    name: "The Dog Spa",
    location: "Manchester, UK",
    badgeTier: "excellent",
    excellenceRank: 9.4,
    category: "groomers",
    imageUrl: "https://images.unsplash.com/photo-1597673030062-0a0f1a801a31?w=400&q=80",
  },
  {
    id: "15",
    slug: "fluffy-tails-grooming",
    name: "Fluffy Tails Grooming Studio",
    location: "Bristol, UK",
    badgeTier: "verified",
    excellenceRank: 9.1,
    category: "groomers",
    imageUrl: "https://images.unsplash.com/photo-1534361960057-19889db9621e?w=400&q=80",
  },
  {
    id: "16",
    slug: "bark-boutique-edinburgh",
    name: "Bark Boutique",
    location: "Edinburgh, UK",
    badgeTier: "excellent",
    excellenceRank: 9.3,
    category: "groomers",
    imageUrl: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=400&q=80",
  },
  {
    id: "17",
    slug: "pampered-pups-birmingham",
    name: "Pampered Pups",
    location: "Birmingham, UK",
    badgeTier: "verified",
    excellenceRank: 9.0,
    category: "groomers",
    imageUrl: "https://images.unsplash.com/photo-1597673030062-0a0f1a801a31?w=400&q=80",
  },
  {
    id: "18",
    slug: "fur-fantastic-leeds",
    name: "Fur Fantastic",
    location: "Leeds, UK",
    badgeTier: "excellent",
    excellenceRank: 9.5,
    category: "groomers",
    imageUrl: "https://images.unsplash.com/photo-1534361960057-19889db9621e?w=400&q=80",
  },
  {
    id: "19",
    slug: "top-dog-grooming-brighton",
    name: "Top Dog Grooming",
    location: "Brighton, UK",
    badgeTier: "verified",
    excellenceRank: 9.2,
    category: "groomers",
    imageUrl: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=400&q=80",
  },
  {
    id: "20",
    slug: "chic-canines-oxford",
    name: "Chic Canines",
    location: "Oxford, UK",
    badgeTier: "outstanding",
    excellenceRank: 9.6,
    category: "groomers",
    imageUrl: "https://images.unsplash.com/photo-1597673030062-0a0f1a801a31?w=400&q=80",
  },
  // Trainers
  {
    id: "21",
    slug: "positive-paws-training",
    name: "Positive Paws Training Academy",
    location: "London, UK",
    badgeTier: "outstanding",
    excellenceRank: 9.8,
    category: "trainers",
    imageUrl: "https://images.unsplash.com/photo-1558929996-da64ba858215?w=400&q=80",
  },
  {
    id: "22",
    slug: "good-boy-school",
    name: "The Good Boy School",
    location: "Manchester, UK",
    badgeTier: "excellent",
    excellenceRank: 9.4,
    category: "trainers",
    imageUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&q=80",
  },
  {
    id: "23",
    slug: "canine-connections-bristol",
    name: "Canine Connections",
    location: "Bristol, UK",
    badgeTier: "verified",
    excellenceRank: 9.1,
    category: "trainers",
    imageUrl: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&q=80",
  },
  {
    id: "24",
    slug: "puppy-stars-birmingham",
    name: "Puppy Stars Training",
    location: "Birmingham, UK",
    badgeTier: "excellent",
    excellenceRank: 9.3,
    category: "trainers",
    imageUrl: "https://images.unsplash.com/photo-1558929996-da64ba858215?w=400&q=80",
  },
  {
    id: "25",
    slug: "behaviour-first-edinburgh",
    name: "Behaviour First",
    location: "Edinburgh, UK",
    badgeTier: "outstanding",
    excellenceRank: 9.7,
    category: "trainers",
    imageUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=400&q=80",
  },
  {
    id: "26",
    slug: "happy-hounds-academy",
    name: "Happy Hounds Academy",
    location: "Leeds, UK",
    badgeTier: "verified",
    excellenceRank: 9.0,
    category: "trainers",
    imageUrl: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=400&q=80",
  },
  // Boarding & Daycare
  {
    id: "27",
    slug: "country-canine-retreat",
    name: "Country Canine Retreat",
    location: "Cotswolds, UK",
    badgeTier: "outstanding",
    excellenceRank: 9.8,
    category: "boarding",
    imageUrl: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&q=80",
  },
  {
    id: "28",
    slug: "happy-tails-daycare",
    name: "Happy Tails Daycare",
    location: "London, UK",
    badgeTier: "excellent",
    excellenceRank: 9.5,
    category: "boarding",
    imageUrl: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&q=80",
  },
  {
    id: "29",
    slug: "pawsome-stays-manchester",
    name: "Pawsome Stays",
    location: "Manchester, UK",
    badgeTier: "verified",
    excellenceRank: 9.2,
    category: "boarding",
    imageUrl: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&q=80",
  },
  {
    id: "30",
    slug: "the-dog-lodge-bristol",
    name: "The Dog Lodge",
    location: "Bristol, UK",
    badgeTier: "excellent",
    excellenceRank: 9.4,
    category: "boarding",
    imageUrl: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&q=80",
  },
  {
    id: "31",
    slug: "pet-paradise-edinburgh",
    name: "Pet Paradise Boarding",
    location: "Edinburgh, UK",
    badgeTier: "outstanding",
    excellenceRank: 9.6,
    category: "boarding",
    imageUrl: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&q=80",
  },
  {
    id: "32",
    slug: "wagging-tails-birmingham",
    name: "Wagging Tails Retreat",
    location: "Birmingham, UK",
    badgeTier: "verified",
    excellenceRank: 9.1,
    category: "boarding",
    imageUrl: "https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=400&q=80",
  },
  // More Vets for additional coverage
  {
    id: "33",
    slug: "cardiff-animal-hospital",
    name: "Cardiff Animal Hospital",
    location: "Cardiff, UK",
    badgeTier: "excellent",
    excellenceRank: 9.3,
    category: "vets",
    imageUrl: "https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?w=400&q=80",
  },
  {
    id: "34",
    slug: "newcastle-pet-clinic",
    name: "Newcastle Pet Clinic",
    location: "Newcastle, UK",
    badgeTier: "verified",
    excellenceRank: 9.0,
    category: "vets",
    imageUrl: "https://images.unsplash.com/photo-1612531386530-97286d97c2d2?w=400&q=80",
  },
  {
    id: "35",
    slug: "sheffield-vets",
    name: "Sheffield Veterinary Centre",
    location: "Sheffield, UK",
    badgeTier: "excellent",
    excellenceRank: 9.4,
    category: "vets",
    imageUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&q=80",
  },
  {
    id: "36",
    slug: "nottingham-pet-care",
    name: "Nottingham Pet Care",
    location: "Nottingham, UK",
    badgeTier: "verified",
    excellenceRank: 9.2,
    category: "vets",
    imageUrl: "https://images.unsplash.com/photo-1551601651-2a8555f1a136?w=400&q=80",
  },
  {
    id: "37",
    slug: "liverpool-animal-hospital",
    name: "Liverpool Animal Hospital",
    location: "Liverpool, UK",
    badgeTier: "outstanding",
    excellenceRank: 9.7,
    category: "vets",
    imageUrl: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=400&q=80",
  },
  {
    id: "38",
    slug: "glasgow-pet-wellness",
    name: "Glasgow Pet Wellness",
    location: "Glasgow, UK",
    badgeTier: "excellent",
    excellenceRank: 9.5,
    category: "vets",
    imageUrl: "https://images.unsplash.com/photo-1628009368231-7bb7cfcb0def?w=400&q=80",
  },
  {
    id: "39",
    slug: "reading-veterinary-practice",
    name: "Reading Veterinary Practice",
    location: "Reading, UK",
    badgeTier: "verified",
    excellenceRank: 9.1,
    category: "vets",
    imageUrl: "https://images.unsplash.com/photo-1612531386530-97286d97c2d2?w=400&q=80",
  },
  {
    id: "40",
    slug: "southampton-pet-hospital",
    name: "Southampton Pet Hospital",
    location: "Southampton, UK",
    badgeTier: "excellent",
    excellenceRank: 9.3,
    category: "vets",
    imageUrl: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&q=80",
  },
];

// Sample practice with full details
export const samplePracticeDetails = {
  id: "1",
  slug: "highgate-veterinary-centre",
  name: "Highgate Veterinary Centre",
  location: "London, UK",
  address: "123 Highgate Hill, London N6 5HE",
  phone: "020 1234 5678",
  email: "info@highgatevet.co.uk",
  website: "https://highgatevet.co.uk",
  badgeTier: "outstanding" as const,
  excellenceRank: 9.8,
  description: "Highgate Veterinary Centre has been serving the local community for over 25 years. Our team of experienced veterinarians and nurses are dedicated to providing the highest standard of care for your pets. We offer a comprehensive range of services including consultations, surgery, dentistry, and emergency care.",
  services: ["General Consultations", "Surgery", "Dentistry", "Emergency Care", "Vaccinations", "Microchipping"],
  openingHours: {
    weekdays: "8:00 AM - 7:00 PM",
    saturday: "9:00 AM - 5:00 PM",
    sunday: "Closed",
  },
  reviews: [
    {
      id: "r1",
      author: "Sarah M.",
      rating: 5,
      date: "2024-02-15",
      text: "Exceptional care for our elderly dog. The staff were incredibly compassionate and professional throughout his treatment.",
      verified: true,
    },
    {
      id: "r2",
      author: "James T.",
      rating: 5,
      date: "2024-02-10",
      text: "Been bringing our cats here for years. Always feel confident they're in good hands.",
      verified: true,
    },
    {
      id: "r3",
      author: "Emma L.",
      rating: 4,
      date: "2024-01-28",
      text: "Great emergency service when our puppy ate something he shouldn't have. Quick response and excellent treatment.",
      verified: true,
    },
  ],
};

// Pillar Guides
export const pillarGuides: Guide[] = [
  {
    slug: "how-to-choose-a-vet",
    title: "How to Choose a Vet: The Complete Guide",
    excerpt: "Everything you need to know about finding the right veterinary practice for your pet, from checking credentials to evaluating facilities.",
    category: "Veterinary",
    readTime: 12,
    isPillar: true,
    imageUrl: "https://images.unsplash.com/photo-1612531386530-97286d97c2d2?w=800&q=80",
  },
  {
    slug: "how-to-choose-a-dog-groomer",
    title: "How to Choose a Dog Groomer",
    excerpt: "A comprehensive guide to finding a professional groomer who will keep your dog looking and feeling their best.",
    category: "Grooming",
    readTime: 8,
    isPillar: true,
    imageUrl: "https://images.unsplash.com/photo-1597673030062-0a0f1a801a31?w=800&q=80",
  },
  {
    slug: "how-to-choose-a-dog-trainer",
    title: "How to Choose a Dog Trainer",
    excerpt: "Learn what to look for in a dog trainer and how to find one whose methods align with your values.",
    category: "Training",
    readTime: 10,
    isPillar: true,
    imageUrl: "https://images.unsplash.com/photo-1558929996-da64ba858215?w=800&q=80",
  },
  {
    slug: "understanding-vet-reviews",
    title: "Understanding Online Vet Reviews",
    excerpt: "How to read between the lines of online reviews and identify genuine feedback from fake or biased reviews.",
    category: "Reviews",
    readTime: 7,
    isPillar: true,
    imageUrl: "https://images.unsplash.com/photo-1512758017271-d7b84c2113f1?w=800&q=80",
  },
];

// Supporting Articles
export const supportingArticles: Guide[] = [
  {
    slug: "what-to-expect-first-vet-visit",
    title: "What to Expect at Your First Vet Visit",
    excerpt: "Preparing for your new pet's first veterinary appointment.",
    category: "Veterinary",
    readTime: 5,
    imageUrl: "https://images.unsplash.com/photo-1583337130417-3346a1be7dee?w=800&q=80",
  },
  {
    slug: "pet-vaccination-schedule",
    title: "Pet Vaccination Schedule: A Complete Guide",
    excerpt: "Understanding which vaccinations your pet needs and when.",
    category: "Health",
    readTime: 6,
    imageUrl: "https://images.unsplash.com/photo-1548767797-d8c844163c4c?w=800&q=80",
  },
  {
    slug: "signs-your-pet-needs-grooming",
    title: "5 Signs Your Pet Needs Professional Grooming",
    excerpt: "How to tell when it's time to book a grooming appointment.",
    category: "Grooming",
    readTime: 4,
    imageUrl: "https://images.unsplash.com/photo-1534361960057-19889db9621e?w=800&q=80",
  },
  {
    slug: "puppy-training-basics",
    title: "Puppy Training Basics: Start Here",
    excerpt: "Essential commands and techniques for new puppy owners.",
    category: "Training",
    readTime: 8,
    imageUrl: "https://images.unsplash.com/photo-1601758228041-f3b2795255f1?w=800&q=80",
  },
  {
    slug: "choosing-pet-insurance",
    title: "How to Choose Pet Insurance",
    excerpt: "Comparing policies and understanding what coverage you really need.",
    category: "Finance",
    readTime: 7,
    imageUrl: "https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=800&q=80",
  },
  {
    slug: "emergency-vet-when-to-go",
    title: "Emergency Vet: When Should You Go?",
    excerpt: "Recognizing the signs that require immediate veterinary attention.",
    category: "Health",
    readTime: 5,
    imageUrl: "https://images.unsplash.com/photo-1576201836106-db1758fd1c97?w=800&q=80",
  },
  {
    slug: "when-to-change-vets",
    title: "When to Change Vets: 7 Warning Signs",
    excerpt: "How to know when it's time to find a new veterinary practice for your pet.",
    category: "Veterinary",
    readTime: 6,
    imageUrl: "https://images.unsplash.com/photo-1612531386530-97286d97c2d2?w=800&q=80",
  },
  {
    slug: "understanding-vet-fees",
    title: "Understanding Vet Fees: What You're Paying For",
    excerpt: "A breakdown of common veterinary costs and how to budget for pet healthcare.",
    category: "Finance",
    readTime: 8,
    imageUrl: "https://images.unsplash.com/photo-1450778869180-41d0601e046e?w=800&q=80",
  },
  {
    slug: "questions-before-booking-groomer",
    title: "10 Questions to Ask Before Booking a Groomer",
    excerpt: "Essential questions to ensure your pet has a safe and positive grooming experience.",
    category: "Grooming",
    readTime: 5,
    imageUrl: "https://images.unsplash.com/photo-1516734212186-a967f81ad0d7?w=800&q=80",
  },
  {
    slug: "dog-anxiety-at-vet",
    title: "Dog Anxiety at the Vet: What Helps",
    excerpt: "Practical tips to reduce your dog's stress during veterinary visits.",
    category: "Health",
    readTime: 7,
    imageUrl: "https://images.unsplash.com/photo-1587300003388-59208cc962cb?w=800&q=80",
  },
  {
    slug: "breed-specific-grooming-needs",
    title: "Breed-Specific Grooming: What Your Dog Needs",
    excerpt: "Understanding the grooming requirements for different coat types and breeds.",
    category: "Grooming",
    readTime: 9,
    imageUrl: "https://images.unsplash.com/photo-1597673030062-0a0f1a801a31?w=800&q=80",
  },
  {
    slug: "positive-vs-punitive-training",
    title: "Positive vs Punitive Training: What to Look For",
    excerpt: "Understanding different training approaches and choosing what's right for your dog.",
    category: "Training",
    readTime: 8,
    imageUrl: "https://images.unsplash.com/photo-1558929996-da64ba858215?w=800&q=80",
  },
];

// Methodology data
export const weightingData = [
  { label: "Clinical Standards", percentage: 45 },
  { label: "Facility Infrastructure", percentage: 35 },
  { label: "Staff Certification", percentage: 20 },
];

export const criteriaData = [
  {
    category: "Medical",
    factor: "Clinical Rigor",
    measurement: "Bi-annual review of on-site medical equipment, emergency protocols, and pharmacy management systems.",
    impact: "critical" as const,
  },
  {
    category: "Operational",
    factor: "Patient Outcomes",
    measurement: "Statistical analysis of recovery rates, secondary infection incidents, and long-term wellness tracking post-discharge.",
    impact: "high" as const,
  },
  {
    category: "Ethical",
    factor: "Transparency Index",
    measurement: "Audit of pricing structures, ownership disclosures, and clarity of customer-facing contracts.",
    impact: "vital" as const,
  },
  {
    category: "Physical",
    factor: "Environmental Safety",
    measurement: "Evaluation of air filtration systems (HEPA), non-porous surface integrity, and sound management for reduced stress.",
    impact: "moderate" as const,
  },
];

export const verificationItems = [
  { label: "Surgical Suite Calibration Records", completed: true },
  { label: "Nurse-to-Patient Ratio (24hr Cover)", completed: true },
  { label: "Post-Op Recovery Outcome Data", completed: true },
  { label: "Bi-Annual CPD Audit Compliance", completed: true },
  { label: "Clinical Waste & Sustainability Protocol", completed: true },
];
